version: "2"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo/chatter
  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/mongodb/db
    ports:
      - "27017:27017"
